sanoma/django-arctic

docs/frontend.md
docs/reference.md

Corrected several typos in docs.

Corrected several typos in docs

---

arctic/generics.py
docs/reference.md
example/articles/views.py
tests/test_virtual_fields.py

Renamed virtual_fields to be more consistent with existing display functionality.
Updated documentation, tests and functionality

Renamed virtual_fields to be more consistent with existing display

---

arctic/generics.py
arctic/users/forms.py

Solved bug #95 by adding additional check for is_active status of user.
Inactive users now can't login.

Solved bug #94: wrong password generation and bug #95: inactive users can login

---

docs/reference.md

Some minor documentation about `users` part of Arctic

Add some documentation for users framework

---

example/articles/views.py
requirements/test.txt
tests/conftest.py
tests/factories.py
tests/test_generics/test_list_view.py
tests/test_layout_mixin.py
tests/test_virtual_fields.py

Related to #107 
Test case for ListView(ArticleListView from example application used) with some obvious checks(including checks for already fixes bug in tool links. 
`factory-boy` is introduced to the project because it looks for me as an easiest way to create multiple objects with minimal efforts. 
@mmarcos , @Silveron please let me know are you agree/disagree with this approach.

Simple test case and factory-boy introducing

---

tests/factories.py
tests/test_users/test_create.py
tests/test_users/test_list.py
tests/test_users/test_update.py

Some basic tests for the `users` views under Arctic(Issue #116 )

Tests for users views

---

arctic/generics.py
arctic/templates/arctic/base.html
arctic/templatetags/arctic_tags.py
docs/reference.md

The problems I've tried to solve with PR are:
* Currently template navbar suppose that user has username field - `USERNAME_FIELD` property in User model
* The same problem as above with detecting in the same place is user logged in or not;
* Login/logout/index urlss hardcoded and there is no way to set custom names;

Add more configuration to urls/USERNAME_FIELD support 

---

arctic/templates/arctic/base_create_update.html

activate abide

---

arctic/generics.py
arctic/utils.py
tests/conftest.py
tests/test_articles.py

make listview compatible with annotated queryset. #57 

---

arctic/templates/arctic/base_create_update.html

This pull request is related to issue #167.

Issue #167 added form action sub block

---

AUTHORS
CHANGELOG.md
arctic/filters.py
requirements/base.txt

Followed this document: https://github.com/carltongibson/django-filter/blob/1.0.0/docs/guide/migration.txt
Searched for stuff that might break and fixed them. Tested with the example project.

bumped django-filter and fixed breaking changes

---

CHANGELOG.md
arctic/generics.py
arctic/mixins.py
docs/reference.md
tests/test_generics/test_update_view.py

you can now add a list of read only fields to an update/detail view

added option for read only fields

---

arctic/generics.py
arctic/templates/arctic/base.html
docs/reference.md
example/dashboard/views.py
tests/test_empty_login_url.py

Allow null login logout urls

---

arctic/generics.py

We have inlines in UpdateView, but we don't have them in CreateView. This PR fixes it.

Change Create view to CreateWithInline

---

arctic/generics.py
arctic/mixins.py
docs/reference.md
tests/test_generics/test_media_assets.py

This PR provides a way to set in settings media assets, that has to be enabled on every page

Common Media assets

---

CHANGELOG.md
arctic/generics.py
arctic/templates/arctic/partials/base_data_table.html
tests/test_generics/test_list_view.py
tests/test_virtual_fields.py

action_links now support urls with multiple parameters

fixed #165 - action_links now support urls with multiple parameters

---

arctic/generics.py
tests/test_virtual_fields.py

Fixes #215  by changing a way of attributes lookup

Fix wrong message

---

AUTHORS
arctic/generics.py
arctic/mixins.py
arctic/templates/arctic/partials/base_data_table.html
docs/reference.md
example/articles/views.py

Added hook to links in order to catch an url click and show a modal dialog.

improve confirmation dialog

---

arctic/templates/arctic/partials/base_data_table.html

250-fixed markup for search form "Search" button

---

CHANGELOG.md
arctic/generics.py
arctic/mixins.py
docs/reference.md
example/articles/views.py
tests/test_generics/test_list_view.py

* improved action_links building
* added field_actions method
* added tests, docs

Action links per row in ListView

---

CHANGELOG.md
arctic/generics.py
arctic/mixins.py
docs/reference.md
example/articles/views.py
tests/test_field_classes.py

* added checking for method `get_{}_field_classes(obj)` 
* small refactor and fixes
* added test
* added doc

customizing `field_classes` per row

---

CHANGELOG.md
arctic/mixins.py
arctic/templates/arctic/partials/base_data_table.html
arctic/templates/arctic/partials/pagination.html
arctic/templatetags/arctic_pagination_tags.py
tests/test_generics/test_list_view.py
tests/test_generics/test_pagination.py

* changed `pagination` block to `bottom_pagination`
* added `top_pagination` block
* added pagination templatetags
* added displaying page number in pagination block

New pagination styles, structure

---

CHANGELOG.md
arctic/forms.py
arctic/templates/arctic/widgets/quick_filters_select.html
arctic/widgets.py
docs/reference.md
example/articles/forms.py
tests/test_forms.py

Implement quick filters types according to [issue](https://github.com/sanoma/django-arctic/issues/282).

implement type of quick filters

---

arctic/generics.py
arctic/templates/arctic/partials/head.html
docs/reference.md

Made it possible to add favicon by just specifying path to it in configuration.
- New feature (non-breaking change which adds functionality)

Added favicon

---

CHANGELOG.md
arctic/templates/arctic/base.html

Wrapped each block of inside base.html with proper classes to easily select it and customize (#323 )

feature/322 wrapped body's blocks into divs with proper classes

---

arctic/generics.py

Include a summary of the change and which issue is fixed.
Fixes #(issue)
Delete options that are not relevant:
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

Strip tags while exporting listview #435

---

.travis.yml
CHANGELOG.md
README.md
arctic/bin/arctic.py
arctic/generics.py
arctic/mixins.py
arctic/models.py
arctic/multiform.py
arctic/project_template/app/views.py
arctic/users/forms.py
arctic/users/views.py
arctic/utils.py
docs/index.md
example/articles/inlines.py
example/articles/models.py
example/articles/views.py
example/config/arctic.py
pyproject.toml
requirements/base.txt
requirements/test.txt
setup.cfg
setup.py
tests/test_utils.py
tox.ini

Added Python 3.8 and Django 3.0 compatibility.
Fixes #441 
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

Added Python 3.8 and Django 3.0 compatibility
